/** Best-effort labels for common Merchant Category Codes (ISO 18245 subset). */
const MCC_NAMES: Record<string, string> = {
  "4111": "Transportation — commuter transport, ferries",
  "4121": "Taxicabs and limousines",
  "4131": "Bus lines",
  "4511": "Airlines, air carriers",
  "4812": "Telecommunication equipment",
  "4814": "Telecommunication services",
  "4900": "Utilities — electric, gas, water, sanitary",
  "5045": "Computers, peripherals, software",
  "5200": "Home supply warehouse stores",
  "5310": "Discount stores",
  "5311": "Department stores",
  "5399": "Miscellaneous general merchandise",
  "5411": "Grocery stores, supermarkets",
  "5422": "Freezer and locker meat provisioners",
  "5441": "Candy, nut, confectionery stores",
  "5451": "Dairy products stores",
  "5462": "Bakeries",
  "5499": "Miscellaneous food stores",
  "5541": "Service stations",
  "5611": "Men's and boys' clothing stores",
  "5621": "Women's ready-to-wear stores",
  "5651": "Family clothing stores",
  "5661": "Shoe stores",
  "5691": "Men's and women's clothing stores",
  "5722": "Household appliance stores",
  "5732": "Electronics stores",
  "5812": "Eating places, restaurants",
  "5813": "Drinking places (bars, taverns)",
  "5814": "Fast food restaurants",
  "5912": "Drug stores, pharmacies",
  "5942": "Book stores",
  "5945": "Hobby, toy, and game shops",
  "5970": "Artist supply stores, craft shops",
  "5977": "Cosmetic stores",
  "5992": "Florists",
  "5999": "Miscellaneous retail",
  "6011": "Financial institutions — manual cash disbursements",
  "6012": "Financial institutions — merchandise and services",
  "7011": "Hotels, motels, resorts",
  "7230": "Beauty and barber shops",
  "7296": "Clothing rental",
  "7299": "Miscellaneous personal services",
  "7832": "Motion picture theaters",
  "7991": "Tourist attractions and exhibits",
  "7995": "Betting, casino gambling",
  "7997": "Membership clubs, country clubs",
  "8011": "Doctors (not elsewhere classified)",
  "8021": "Dentists, orthodontists",
  "8062": "Hospitals",
  "8099": "Health practitioners, medical services (n.e.c.)",
  "8211": "Elementary and secondary schools",
  "8220": "Colleges, universities",
  "8351": "Child care services",
  "8398": "Charitable and social service organizations",
};

export function getMerchantCategoryName(code: string): string | undefined {
  return MCC_NAMES[code];
}
